import:
  - data
  - kernel-demo
  - implot-demo
  - tab-demo
  - foreach-key-demo
  - table-demo
  - widgets-demo
  - tooltip-demo
  - popups-demo

widgets:
  main-window:
    type: imgui-main-window
    label: "Ymery Widget Demo"
    window-size: [1200, 800]
    fps-idle: 0
    body:
      - text: "Widget System Demo"
      - separator
      # Upper part: Demo tabs
      - child:
          size: [0, -200]
          body:
            - tab-bar:
                label: "Demo Tabs"
                tooltip: "Main demo tabs - each tab demonstrates different widget features and data binding patterns."
                body:
                  - tab-item:
                      label: "Kernel"
                      tooltip: "Kernel data source demo. Shows live system tree with recursive tree-node, selection binding, on-hover metadata tooltips, and style-mapping."
                      body:
                        - kernel-demo.kernel-demo-tab:
                  - tab-item:
                      label: "ImPlot"
                      tooltip: "ImPlot integration demo. Shows waveform plotting with multiple layers bound to kernel waveform providers via data-path."
                      body:
                        - implot-demo.implot-demo-tab:
                  - tab-item:
                      label: "Tab Widget"
                      tooltip: "Tab-bar and tab-item demo. Shows nested tabs with various input widgets bound to local data-tree."
                      body:
                        - tab-demo.tab-demo-tab:
                  - tab-item:
                      label: "Foreach-Key"
                      tooltip: "Foreach-key iterator demo. Shows how to iterate over metadata keys using $key and $value placeholders."
                      body:
                        - foreach-key-demo.foreach-key-demo-tab:
                  - tab-item:
                      label: "Table"
                      tooltip: "ImGui table demo. Shows table with rows, columns, header flags, and static content."
                      body:
                        - table-demo.table-demo-tab:
                  - tab-item:
                      label: "Widgets"
                      tooltip: "Comprehensive widget demo. Shows text, buttons, tree-nodes, and input widgets with static vs dynamic data binding."
                      body:
                        - widgets-demo.widgets-demo-tab:
                  - tab-item:
                      label: "Tooltips"
                      tooltip: "Tooltip widget demo. Shows implicit tooltips (via 'tooltip' static) and explicit tooltips (tooltip widget with body)."
                      body:
                        - tooltip-demo.tooltip-demo-tab:
                  - tab-item:
                      label: "Popups"
                      tooltip: "Popup widget demo. Shows buttons that open modal popups containing other demos."
                      body:
                        - popups-demo.popups-demo-tab:
      - separator
      # Lower part: Application Logs
      - text: "Application Logs:"
      - child:
          size: [0, 0]
          border: true
          body:
            - data-path: $log-tree
              builtin.tree-view:

app:
  widget: app.main-window
  main-data: demo-data
