import:
  - widgets
  - data

widgets:
  error-tree-demo-popup:
    type: popup
    body:
      - text: "Error Tree Demo - builtin.tree-view"
      - separator
      - data-path: error-data
        builtin.tree-view:

  main-window:
    type: imgui-main-window
    window-title: "Ymery Widget Demo"
    window-size: [1200, 800]
    fps-idle: 0
    body:
      - text: "Widget System Demo"
      - separator
      - button:
          label: "Widgets Demo"
          body: widgets.widgets-demo-popup
      - same-line
      - button:
          label: "Kernel Demo"
          body: widgets.kernel-demo-popup
      - same-line
      - button:
          label: "Implot Demo"
          body: widgets.implot-demo-popup
      - same-line
      - button:
          label: "Foreach-Key Demo"
          body: widgets.foreach-key-demo-popup
      - same-line
      - button:
          label: "Table Demo"
          body: widgets.table-demo-popup
      - same-line
      - button:
          label: "Tab Demo"
          body: widgets.tab-demo-popup
      - same-line
      - button:
          label: "Modal Popup"
          body: widgets.popup-modal-demo-content
      - same-line
      - button:
          label: "Error Tree Demo"
          body: app.error-tree-demo-popup
      - separator
      - text: "Draggable Button Demo:"
      - data-path: # we leave it empty (python: None) so that the widget does not inherit any data
        draggable:
          head:
            size: [40, 40]
            position: [50, 50]
            bounds: window
          body:
            - button:
                head:
                  label: "this is a button label"
                  tooltip: "Drag me anywhere in the window"
                body: widgets.draggable-demo-popup
      - separator
      - text: "Live Data (updates as you edit):"

app:
  widget: app.main-window
  main-data: demo-data
