import:
  - data
  - kernel-demo
  - implot-demo
  - tab-demo
  - foreach-key-demo
  - table-demo
  - widgets-demo

widgets:
  main-window:
    type: imgui-main-window
    window-title: "Ymery Widget Demo"
    window-size: [1200, 800]
    fps-idle: 0
    body:
      - text: "Widget System Demo"
      - separator
      # Upper part: Demo tabs
      - child:
          size: [0, -200]
          body:
            - tab-bar:
                label: "Demo Tabs"
                body:
                  - tab-item:
                      label: "Kernel"
                      body:
                        - kernel-demo.kernel-demo-tab:
                  - tab-item:
                      label: "ImPlot"
                      body:
                        - implot-demo.implot-demo-tab:
                  - tab-item:
                      label: "Tab Widget"
                      body:
                        - tab-demo.tab-demo-tab:
                  - tab-item:
                      label: "Foreach-Key"
                      body:
                        - foreach-key-demo.foreach-key-demo-tab:
                  - tab-item:
                      label: "Table"
                      body:
                        - table-demo.table-demo-tab:
                  - tab-item:
                      label: "Widgets"
                      body:
                        - widgets-demo.widgets-demo-tab:
      - separator
      # Lower part: Application Logs
      - text: "Application Logs:"
      - child:
          size: [0, 0]
          border: true
          body:
            - data-path: $log-tree
              builtin.tree-view:

app:
  widget: app.main-window
  main-data: demo-data
