import:
  - widgets

widgets:
  error-tree-demo-popup:
    type: popup
    body:
      - text: "Error Tree Demo - builtin.tree-view"
      - separator
      - data-path: error-data
        builtin.tree-view:

  main-window:
    type: imgui-main-window
    window-title: "Imery Widget Demo"
    window-size: [1200, 800]
    fps-idle: 0
    body:
      - text: "Widget System Demo"
      - separator
      - button:
          label: "Widgets Demo"
          body: widgets.widgets-demo-popup
      - same-line
      - button:
          label: "Kernel Demo"
          body: widgets.kernel-demo-popup
      - same-line
      - button:
          label: "Implot Demo"
          body: widgets.implot-demo-popup
      - same-line
      - button:
          label: "Foreach-Key Demo"
          body: widgets.foreach-key-demo-popup
      - same-line
      - button:
          label: "Table Demo"
          body: widgets.table-demo-popup
      - same-line
      - button:
          label: "Tab Demo"
          body: widgets.tab-demo-popup
      - same-line
      - button:
          label: "Modal Popup"
          body: widgets.popup-modal-demo-content
      - same-line
      - button:
          label: "Error Tree Demo"
          body: app.error-tree-demo-popup
      - separator
      - text: "Draggable Button Demo:"
      - data-path: # we leave it empty (python: None) so that the widget does not inherit any data
        draggable:
          head:
            size: [40, 40]
            position: [50, 50]
            bounds: window
          body:
            - button:
                head:
                  label: "this is a button label"
                  tooltip: "Drag me anywhere in the window"
                body: widgets.draggable-demo-popup
      - separator
      - text: "Live Data (updates as you edit):"

data:
  demo-data:
    metadata:
      label: "Demo Root"
    children:
      error-data:
        metadata:
          label: "Error:"
        children:
          error:
            metadata:
              label: "Widget: render: detect_and_execute_events failed"
            children:
              prev_error:
                metadata:
                  label: "Failed to execute 'on-click' commands"
                children:
                  error:
                    metadata:
                      label: "Widget: _execute_event_command_dispatch_event: not implemented"
      kernel-tree:
        metadata:
          selection: None
      kernel: $kernel
      # Text widget demos
      text-single:
        metadata:
          label: "Single dynamic text value"
      text-dict:
        metadata:
          label: "Text Dict"
        children:
          first:
            metadata:
              label: "First text"
          second:
            metadata:
              label: "Second text"
          third:
            metadata:
              label: "Third text"
      # BulletText widget demos
      bullet-single:
        metadata:
          label: "Single bullet point"
      bullet-dict:
        metadata:
          label: "Bullet Dict"
        children:
          feature1:
            metadata:
              label: "Feature One"
          feature2:
            metadata:
              label: "Feature Two"
          feature3:
            metadata:
              label: "Feature Three"
      # SeparatorText widget demos
      separator-single:
        metadata:
          label: "Single Section Title"
      separator-dict:
        metadata:
          label: "Separator Dict"
        children:
          intro:
            metadata:
              label: "Introduction"
          main:
            metadata:
              label: "Main Content"
          conclusion:
            metadata:
              label: "Conclusion"
      # Button widget demos
      button-single:
        metadata:
          label: "Click Me"
      button-dict:
        metadata:
          label: "Button Dict"
        children:
          save:
            metadata:
              label: "Save"
          load:
            metadata:
              label: "Load"
          delete:
            metadata:
              label: "Delete"
      # TreeNode widget demos
      tree-single:
        metadata:
          label: "Single Tree Node"
      tree-dict:
        metadata:
          label: "Tree Dict"
        children:
          node1:
            metadata:
              label: "First Node"
          node2:
            metadata:
              label: "Second Node"
          node3:
            metadata:
              label: "Third Node"
      # CollapsingHeader widget demos
      collapse-single:
        metadata:
          label: "Single Collapsing Section"
      collapse-dict:
        metadata:
          label: "Collapse Dict"
        children:
          settings:
            metadata:
              label: "Settings"
          advanced:
            metadata:
              label: "Advanced"
          debug:
            metadata:
              label: "Debug"
      # Menu widget demos
      menu-single:
        metadata:
          label: "Main Menu"
      menu-dict:
        metadata:
          label: "Menu Dict"
        children:
          file:
            metadata:
              label: "File"
          edit:
            metadata:
              label: "Edit"
          view:
            metadata:
              label: "View"
      # MenuItem widget demos
      menuitem-single:
        metadata:
          label: "Menu Action"
      menuitem-dict:
        metadata:
          label: "MenuItem Dict"
        children:
          new:
            metadata:
              label: "New"
          open:
            metadata:
              label: "Open"
          close:
            metadata:
              label: "Close"
      # Input widgets (require single values)
      input-text:
        metadata:
          label: "Editable text"
      input-int:
        metadata:
          label: "42"
      slider-int:
        metadata:
          label: "50"
      slider-float:
        metadata:
          label: "0.5"
      combo:
        metadata:
          label: "Option A"
      checkbox:
        metadata:
          label: "True"
      # Color widgets
      color-edit:
        metadata:
          label: [1.0, 0.5, 0.2, 1.0]
      color-button:
        metadata:
          label: [0.2, 0.7, 1.0, 1.0]

app:
  widget: app.main-window
  data: demo-data
