import:
  - widgets
  - menu
  - data


widgets:
  # ============================================================================
  # MAIN WINDOW
  # ============================================================================
  main-widget:
    type: hello-imgui-main-window
    label: "Imery widget editor"
    runner-params:
      app-window-params:
        window-geometry:
          size: [1600, 1000]
      imgui-window-params:
        default-imgui-window-type: provide-full-screen-dock-space
    fps-idle: 0
    body:
      - main-menu-bar:
          body:
            menu.menu-bar-content:

      # Docking splits
      - docking-split:
          initial-dock: "MainDockSpace"
          new-dock: "BottomPanel"
          direction: "down"
          ratio: 0.25
      - docking-split:
          initial-dock: "MainDockSpace"
          new-dock: "LeftPanel"
          direction: "left"
          ratio: 0.25

      # Dockable windows
      - dockable-window:
          label: "Kernel Browser"
          dock-space-name: "LeftPanel"
          body:
            - data-path: kernel
              kernel.kernel-tree-view:
      - dockable-window:
          label: "Plots"
          dock-space-name: "MainDockSpace"
          body:
            - data-path: plots
              implot.implot-wrapper-stack:
      - dockable-window:
          label: "Errors"
          dock-space-name: "BottomPanel"
          body:
            - widgets.error-view:
      - dockable-window:
          label: "Logs"
          dock-space-name: "BottomPanel"
          body:
            - widgets.logs-view:
      - dockable-window:
          label: "Data"
          dock-space-name: "BottomPanel"
          body:
            - widgets.data-view:


app:
  widget: app.main-widget
  data: waew-data
