import:
  - hello-imgui-widgets
  - data
  - widgets.basic
  - widgets.tables
  - widgets.layout
  - widgets.popups
  - widgets.trees
  - widgets.tabs
  - widgets.colors
  - widgets.combos
  - widgets.text
  - widgets.tooltips
  - widgets.selectables
  - widgets.drags
  - widgets.listboxes
  - widgets.images
  - widgets.bullets
  - examples.console
  - examples.log
  - examples.layout-example
  - examples.property-editor
  - examples.long-text
  - examples.command-palette
  - examples.drag-and-drop
  - examples.matplotlib-demo
  - examples.custom-background
  - examples.docking-demo
  - examples.implot-demo
  - examples.implot3d-demo
  - examples.markdown-demo
  - examples.node-editor-demo
  - examples.text-editor-demo
  - examples.immvision-demo
  # - examples.nanovg-demo
  - examples.imguizmo-demo
  - examples.tex-inspect-demo
  - examples.widgets-demo

widgets:
  # ============================================================================
  # MAIN WINDOW with Docking
  # ============================================================================
  main-window:
    type: hello-imgui-main-window
    runner-params:
      app-window-params:
        window-geometry:
          size: [1600, 1000]
      imgui-window-params:
        default-imgui-window-type: provide-full-screen-dock-space
    fps-idle: 0
    body:
    # Main Window Menu
    - hello-imgui-menu:
        body:
          - menu:
              label: "File"
              body:
                - menu-item:
                    label: "Open"
                - menu-item:
                    label: "Save"
                - separator:
                - menu-item:
                    label: "Exit"

          - menu:
              label: "View"
              body:
                - menu-item:
                    label: "Docking"

    - hello-imgui-app-menu-items:
        body:
          - menu-item:
              label: "About"

    # ============================================================================
    # DOCKING LAYOUT
    # ============================================================================

    # Bottom panel for logs
    - docking-split:
        initial-dock: "MainDockSpace"
        new-dock: "BottomPanel"
        direction: "down"
        ratio: 0.2

    # ============================================================================
    # MAIN PANEL - All demos tabbed
    # ============================================================================

    - dockable-window:
        label: "Intro"
        dock-space-name: "MainDockSpace"
        body:
          - text: "Welcome to Dear ImGui Bundle Demo"
          - separator:
          - text: "This is a comprehensive demo of all ImGui Bundle features"

    - dockable-window:
        label: "Dear ImGui"
        dock-space-name: "MainDockSpace"
        body:
          - menu-bar:
              body:
                - menu:
                    label: "Examples"
                    body:
                      - separator-text: "Mini apps"
                      - menu-item:
                          label: "Console"
                      - menu-item:
                          label: "Log"
                      - menu-item:
                          label: "Simple layout"
                      - menu-item:
                          label: "Property editor"
                      - separator-text: "Concepts"
                      - menu-item:
                          label: "Long text display"
                - menu:
                    label: "Tools"
                    body:
                      - menu-item:
                          label: "Metrics/Debugger"
                      - menu-item:
                          label: "Debug Log"
                      - menu-item:
                          label: "Style Editor"
                      - menu-item:
                          label: "About Dear ImGui"

          - collapsing-header:
              label: "Widgets"
              flags: [default-open]
              body:
                - tree-node:
                    label: "Basic"
                    flags: [default-open]
                    body:
                      - data-path: basic-demo-data
                        widgets.basic.basic-demo:
                - tree-node:
                    label: "Tooltips"
                    body:
                      - widgets.tooltips.tooltips-demo:
                - tree-node:
                    label: "Tree Nodes"
                    body:
                      - widgets.trees.trees-demo:
                - tree-node:
                    label: "Bullets"
                    body:
                      - widgets.bullets.bullets-demo:
                - tree-node:
                    label: "Text"
                    body:
                      - widgets.text.text-demo:
                - tree-node:
                    label: "Images"
                    body:
                      - widgets.images.images-demo:
                - tree-node:
                    label: "Combo"
                    body:
                      - widgets.combos.combos-demo:
                - tree-node:
                    label: "List Boxes"
                    body:
                      - widgets.listboxes.listboxes-demo:
                - tree-node:
                    label: "Selectables"
                    body:
                      - widgets.selectables.selectables-demo:
                - tree-node:
                    label: "Drags"
                    body:
                      - widgets.drags.drags-demo:
                - tree-node:
                    label: "Tabs"
                    body:
                      - widgets.tabs.tabs-demo:
                - tree-node:
                    label: "Colors"
                    body:
                      - widgets.colors.colors-demo:

          - collapsing-header:
              label: "Layout & Scrolling"
              body:
                - widgets.layout.layout-demo:

          - collapsing-header:
              label: "Popups & Modal windows"
              body:
                - widgets.popups.popups-demo:

          - collapsing-header:
              label: "Tables & Columns"
              body:
                - widgets.tables.tables-demo:

    - dockable-window:
        label: "Demo Apps"
        dock-space-name: "MainDockSpace"
        body:
          - markdown: |
              # HelloImGui and ImmApp

              * [HelloImGui](https://pthom.github.io/hello_imgui) is a library based on ImGui that enables to easily create applications with ImGui.
              * [ImApp](https://github.com/pthom/imgui_bundle/blob/main/external/immapp/immapp/runner.h) (aka "Immediate App", a submodule of ImGuiBundle) is a thin extension of HelloImGui that enables to easily initialize the ImGuiBundle addons that require additional setup at startup.

              ## Demo applications

          - separator:

          - collapsing-header:
              label: "Command Palette"
              body:
                - examples.command-palette.command-palette:

          - collapsing-header:
              label: "Drag and Drop"
              body:
                - examples.drag-and-drop.drag-and-drop:

          - collapsing-header:
              label: "Custom Background"
              body:
                - examples.custom-background.custom-background:

          - collapsing-header:
              label: "Docking"
              body:
                - examples.docking-demo.docking-demo:

          - collapsing-header:
              label: "Matplotlib"
              body:
                - examples.matplotlib-demo.matplotlib-demo:

    - dockable-window:
        label: "Implot [3D]"
        dock-space-name: "MainDockSpace"
        body:
          - collapsing-header:
              label: "ImPlot"
              flags: [default-open]
              body:
                - examples.implot-demo.implot-demo:

          - collapsing-header:
              label: "ImPlot 3D"
              body:
                - examples.implot3d-demo.implot3d-demo:

    - dockable-window:
        label: "Node Editor"
        dock-space-name: "MainDockSpace"
        body:
          - examples.node-editor-demo.node-editor-demo:

    - dockable-window:
        label: "Markdown"
        dock-space-name: "MainDockSpace"
        body:
          - examples.markdown-demo.markdown-demo:

    - dockable-window:
        label: "Text Editor"
        dock-space-name: "MainDockSpace"
        body:
          - examples.text-editor-demo.text-editor-demo:

    - dockable-window:
        label: "Widgets"
        dock-space-name: "MainDockSpace"
        body:
          - examples.widgets-demo.widgets-demo:

    - dockable-window:
        label: "ImmVision"
        dock-space-name: "MainDockSpace"
        body:
          - examples.immvision-demo.immvision-demo:

    - dockable-window:
        label: "ImGuizmo"
        dock-space-name: "MainDockSpace"
        body:
          - examples.imguizmo-demo.imguizmo-demo:

    - dockable-window:
        label: "Themes"
        dock-space-name: "MainDockSpace"
        body:
          - text: "Theme selector will go here"

    - dockable-window:
        label: "tex_inspect"
        dock-space-name: "MainDockSpace"
        body:
          - examples.tex-inspect-demo.tex-inspect-demo:

    # ============================================================================
    # BOTTOM PANEL - Logs
    # ============================================================================
    - dockable-window:
        label: "Logs"
        dock-space-name: "BottomPanel"
        body:
          - hello-imgui-widgets.logs-view:


app:
  widget: app.main-window
  data: demo-data
